# Download Pokemon sprites for Owl's Nest Wiki
$ErrorActionPreference = "Continue"
$spriteDir = "static/img/pokemon"
New-Item -ItemType Directory -Force -Path $spriteDir | Out-Null
$sprites = @(
  @{ file = "aegislash.png"; slugs = @("aegislash") },
  @{ file = "aerodactyl.png"; slugs = @("aerodactyl") },
  @{ file = "aggron.png"; slugs = @("aggron") },
  @{ file = "alakazam.png"; slugs = @("alakazam") },
  @{ file = "annihilape.png"; slugs = @("annihilape") },
  @{ file = "arbok.png"; slugs = @("arbok") },
  @{ file = "arcanine.png"; slugs = @("arcanine") },
  @{ file = "arceus.png"; slugs = @("arceus") },
  @{ file = "archaludon.png"; slugs = @("archaludon") },
  @{ file = "articuno.png"; slugs = @("articuno") },
  @{ file = "azumarill.png"; slugs = @("azumarill") },
  @{ file = "basculegion.png"; slugs = @("basculegion") },
  @{ file = "baxcalibur.png"; slugs = @("baxcalibur") },
  @{ file = "blastoise.png"; slugs = @("blastoise") },
  @{ file = "breloom.png"; slugs = @("breloom") },
  @{ file = "butterfree.png"; slugs = @("butterfree") },
  @{ file = "ceruledge.png"; slugs = @("ceruledge") },
  @{ file = "cetitan.png"; slugs = @("cetitan") },
  @{ file = "chandelure.png"; slugs = @("chandelure") },
  @{ file = "charizard.png"; slugs = @("charizard") },
  @{ file = "chienpao.png"; slugs = @("chienpao", "chien-pao") },
  @{ file = "conkeldurr.png"; slugs = @("conkeldurr") },
  @{ file = "cursola.png"; slugs = @("cursola") },
  @{ file = "dragalge.png"; slugs = @("dragalge") },
  @{ file = "dragapult.png"; slugs = @("dragapult") },
  @{ file = "dragonite.png"; slugs = @("dragonite") },
  @{ file = "drampa.png"; slugs = @("drampa") },
  @{ file = "drilbur.png"; slugs = @("drilbur") },
  @{ file = "dustox.png"; slugs = @("dustox") },
  @{ file = "eelektross.png"; slugs = @("eelektross") },
  @{ file = "excadrill.png"; slugs = @("excadrill") },
  @{ file = "ferrothorn.png"; slugs = @("ferrothorn") },
  @{ file = "flareon.png"; slugs = @("flareon") },
  @{ file = "fluttermane.png"; slugs = @("fluttermane", "flutter-mane") },
  @{ file = "froslass.png"; slugs = @("froslass") },
  @{ file = "gabite.png"; slugs = @("gabite") },
  @{ file = "gallade.png"; slugs = @("gallade") },
  @{ file = "garchomp.png"; slugs = @("garchomp") },
  @{ file = "gardevoir.png"; slugs = @("gardevoir") },
  @{ file = "gengar.png"; slugs = @("gengar") },
  @{ file = "gholdengo.png"; slugs = @("gholdengo") },
  @{ file = "gible.png"; slugs = @("gible") },
  @{ file = "glaceon.png"; slugs = @("glaceon") },
  @{ file = "gligar.png"; slugs = @("gligar") },
  @{ file = "golem.png"; slugs = @("golem") },
  @{ file = "gougingfire.png"; slugs = @("gougingfire", "gouging-fire") },
  @{ file = "greninja.png"; slugs = @("greninja") },
  @{ file = "grimmsnarl.png"; slugs = @("grimmsnarl") },
  @{ file = "groudon.png"; slugs = @("groudon") },
  @{ file = "guzzlord.png"; slugs = @("guzzlord") },
  @{ file = "gyarados.png"; slugs = @("gyarados") },
  @{ file = "hariyama.png"; slugs = @("hariyama") },
  @{ file = "houndoom.png"; slugs = @("houndoom") },
  @{ file = "houndstone.png"; slugs = @("houndstone") },
  @{ file = "hydrapple.png"; slugs = @("hydrapple") },
  @{ file = "hydreigon.png"; slugs = @("hydreigon") },
  @{ file = "incineroar.png"; slugs = @("incineroar") },
  @{ file = "iron_moth.png"; slugs = @("ironmoth", "iron-moth", "iron_moth") },
  @{ file = "ironhands.png"; slugs = @("ironhands", "iron-hands") },
  @{ file = "jolteon.png"; slugs = @("jolteon") },
  @{ file = "kingambit.png"; slugs = @("kingambit") },
  @{ file = "kingdra.png"; slugs = @("kingdra") },
  @{ file = "krookodile.png"; slugs = @("krookodile") },
  @{ file = "larvitar.png"; slugs = @("larvitar") },
  @{ file = "latios.png"; slugs = @("latios") },
  @{ file = "leafeon.png"; slugs = @("leafeon") },
  @{ file = "luxray.png"; slugs = @("luxray") },
  @{ file = "lycanroc.png"; slugs = @("lycanroc") },
  @{ file = "mabosstiff.png"; slugs = @("mabosstiff") },
  @{ file = "machamp.png"; slugs = @("machamp") },
  @{ file = "mamoswine.png"; slugs = @("mamoswine") },
  @{ file = "meganium.png"; slugs = @("meganium") },
  @{ file = "meowscarada.png"; slugs = @("meowscarada") },
  @{ file = "metagross.png"; slugs = @("metagross") },
  @{ file = "mewtwo.png"; slugs = @("mewtwo") },
  @{ file = "miraidon.png"; slugs = @("miraidon") },
  @{ file = "moltres.png"; slugs = @("moltres") },
  @{ file = "nidoking.png"; slugs = @("nidoking") },
  @{ file = "nidoqueen.png"; slugs = @("nidoqueen") },
  @{ file = "nidoranm.png"; slugs = @("nidoran-m", "nidoranm") },
  @{ file = "nidorino.png"; slugs = @("nidorino") },
  @{ file = "ninetales.png"; slugs = @("ninetales") },
  @{ file = "noibat.png"; slugs = @("noibat") },
  @{ file = "pelipper.png"; slugs = @("pelipper") },
  @{ file = "politoed.png"; slugs = @("politoed") },
  @{ file = "primarina.png"; slugs = @("primarina") },
  @{ file = "pupitar.png"; slugs = @("pupitar") },
  @{ file = "pyroar.png"; slugs = @("pyroar") },
  @{ file = "ragingbolt.png"; slugs = @("ragingbolt", "raging-bolt") },
  @{ file = "raichu.png"; slugs = @("raichu") },
  @{ file = "rayquaza.png"; slugs = @("rayquaza") },
  @{ file = "regieleki.png"; slugs = @("regieleki") },
  @{ file = "rillaboom.png"; slugs = @("rillaboom") },
  @{ file = "roaringmoon.png"; slugs = @("roaringmoon", "roaring-moon") },
  @{ file = "salamence.png"; slugs = @("salamence") },
  @{ file = "scyther.png"; slugs = @("scyther") },
  @{ file = "servine.png"; slugs = @("servine") },
  @{ file = "seviper.png"; slugs = @("seviper") },
  @{ file = "sharpedo.png"; slugs = @("sharpedo") },
  @{ file = "shedinja.png"; slugs = @("shedinja") },
  @{ file = "silicobra.png"; slugs = @("silicobra") },
  @{ file = "sneasler.png"; slugs = @("sneasler") },
  @{ file = "snorlax.png"; slugs = @("snorlax") },
  @{ file = "swoobat.png"; slugs = @("swoobat") },
  @{ file = "tinglu.png"; slugs = @("tinglu", "ting-lu") },
  @{ file = "toxapex.png"; slugs = @("toxapex") },
  @{ file = "toxtricity.png"; slugs = @("toxtricity") },
  @{ file = "tyranitar.png"; slugs = @("tyranitar") },
  @{ file = "umbreon.png"; slugs = @("umbreon") },
  @{ file = "urshifu.png"; slugs = @("urshifu") },
  @{ file = "vanilluxe.png"; slugs = @("vanilluxe") },
  @{ file = "venusaur.png"; slugs = @("venusaur") },
  @{ file = "wailord.png"; slugs = @("wailord") },
  @{ file = "walkingwake.png"; slugs = @("walkingwake", "walking-wake") },
  @{ file = "whimsicott.png"; slugs = @("whimsicott") },
  @{ file = "zamazenta.png"; slugs = @("zamazenta") },
  @{ file = "zoroark.png"; slugs = @("zoroark") },
  @{ file = "zubat.png"; slugs = @("zubat") }
)

foreach ($sprite in $sprites) {
  $dest = Join-Path $spriteDir $sprite.file
  if (Test-Path $dest) { Write-Host "Already exists: $dest"; continue }
  $ok = $false
  foreach ($slug in $sprite.slugs) {
    $url = "https://play.pokemonshowdown.com/sprites/dex/$slug.png"
    try {
      Invoke-WebRequest -UseBasicParsing -Uri $url -OutFile $dest
      if ((Test-Path $dest) -and ((Get-Item $dest).Length -gt 100)) {
        Write-Host "Downloaded $($sprite.file) from $slug"
        $ok = $true
        break
      }
    } catch {
      if (Test-Path $dest) { Remove-Item -Force $dest }
    }
  }
  if (-not $ok) { Write-Warning "Could not download $($sprite.file)" }
}
